import { API_URL } from "@/config/api";

export async function getHomeData (): Promise<HomeDataResponse> {
    const response = await fetch(`${API_URL}/posts/find/home`);
    const data = await response.json();
    return data;
}

// Generated by https://quicktype.io

export interface HomeDataResponse {
    top:       Post[];
    secondary: Post[];
    extras:    Post[];
    tubes:     Post[];
    reads:     Post[];
}

export interface Post {
    title:        string;
    author:       string;
    authorImage:  string;
    slug?:         string;
    link?:         string;
    image?:        string;
    category:     Category;
    subcategory?: string;
}

export enum Category {
    EduBits = "edu-bits",
    EduNews = "edu-news",
    EduReads = "edu-reads",
    EduTube = "edu-tubes",
    Podcast = 'edutrendspodcast',
    Editorial = "editorial",
}
