import { API_URL } from "@/config/api";
import { Post } from "./posts";

export async function getHomeData(): Promise<HomeDataResponse> {
  const response = await fetch(`${API_URL}/posts/find/home`);
  const data = await response.json();
  return data;
}

// Generated by https://quicktype.io

export interface HomeDataResponse {
  top: Post[];
  secondary: Post[];
  extras: Post[];
  tubes: Post[];
  reads: Post[];
}

export enum Category {
  NEWS = "edu-news",
  BITS = "edu-bits",
  READS = "edu-reads",
  TUBES = "edu-tubes",
  // PODCAST = 'edutrendspodcast',
  PODCAST = "edu-podcast",
  Editorial = "edu-editorial",
}
